let inscriptions = [
    ["bib","lastname","firstname","category","gender","status"],
    ["200","LE GALLIC","Ludovic","Masters 30","Homme","Validée"],
    ["201","GICQUEL","David","Masters 30","Homme","Validée"],
    ["202","LAMBERT","Pascal","Masters 40","Homme","Validée"],
    ["203","GUY","NICOLAS","Masters 30","Homme","Validée"],
    ["204","LE MOIGNE","Luca","Masters 30","Homme","Validée"],
    ["205","RIVOALLON","Gaétan","Seniors","Homme","Validée"],
    ["206","TURCO","Gilles","Masters 40","Homme","Validée"],
    ["207","DELVOIE","Jeremie","Masters 40","Homme","Validée"],
    ["208","MONNIER","Tanguy","Masters 40","Homme","Validée"],
    ["209","MONNIER","Nolan","Cadets","Homme","Validée"],
    ["210","LE CLECH","Hugo","Cadets","Homme","Validée"],
    ["211","LE CLECH","David","Masters 40","Homme","Validée"],
    ["300","BALCH","STEPHANE","Masters 40","Homme","Validée"],
    ["301","GLAZIOU","Anthony","Masters 30","Homme","Validée"],
    ["302","GUELAFF","Yan","Masters 40","Homme","Validée"],
    ["303","JOLIVET","Cindy","Seniors","Femme","Validée"],
    ["304","TOURNELLEC","Marc","Masters 40","Homme","Validée"],
    ["305","LE HIR","Mickael","Masters 30","Homme","Validée"],
    ["306","FRANCOIS","LAURENT","Masters 50+","Homme","Validée"],
    ["307","PLUVINAGE","COME","Minimes","Homme","Validée"],
    ["308","DELANNEE","MATTEO","Minimes","Homme","Validée"],
    ["309","BRETEL","DYLAN","Cadets","Homme","Validée"],
    ["310","MONCORPS MERCIER","BERYL","Minimes","Homme","Validée"],
    ["311","LEBOURCIER","ENZO","Minimes","Homme","Validée"],
    ["312","ROUE","Gerald","Masters 40","Homme","Validée"],
    ["313","MALABOUS","Julien","Masters 30","Homme","Validée"],
    ["314","DELABYE","Théo","Seniors","Homme","Validée"],
    ["315","GOUBILL","Cyril","Masters 40","Homme","Validée"],
    ["316","BEUGEL","Marc","Masters 40","Homme","Validée"],
    ["317","PEROT","Nicolas","Masters 40","Homme","Validée"],
    ["318","LE CLOAREC","Kevin","Minimes","Homme","Validée"],
    ["319","PELLÉ","Jules","Minimes","Homme","Validée"],
    ["321","EVEN","Florian","Masters 30","Homme","Validée"],
    ["322","LE GOUX","Théo","Cadets","Homme","Validée"],
    ["323","LE DEZ","Robin","Juniors","Homme","Validée"],
    ["324","PLANTEC","Georges","Masters 50+","Homme","Validée"],
    ["325","PLANTEC","Goulven","Minimes","Homme","Validée"],
    ["326","PLANTEC","Fanch","Juniors","Homme","Validée"],
    ["327","LE CLECH","Stephane","Masters 40","Homme","Validée"],
    ["328","LE MOAL","RENAN","Masters 40","Homme","Validée"],
    ["329","PASQUIER","Christian","Masters 50+","Homme","Validée"],
    ["330","HUET","Julien","Masters 30","Homme","Validée"],
    ["331","VERBERT","Johann","Masters 40","Homme","Validée"],
    ["332","HECQUET","Kevin","Masters 30","Homme","Validée"],
    ["333","LE ROI","Jean pierre","Pupilles","Homme","Validée"],
    ["334","LE ROI","Jean yves","Masters 50+","Homme","Validée"],
    ["335","GUEVEL","Jean luc","Masters 40","Homme","Validée"],
    ["336","SERCLÉRAT","Benjamin","Cadets","Homme","Validée"],
    ["337","CREFF","Noah","Cadets","Homme","Validée"],
    ["338","FERRÉ","Achille","Cadets","Homme","Validée"],
    ["339","GUILLERM","Charles","Masters 30","Homme","Validée"],
    ["340","GUILLERM","Noah","Benjamins","Homme","Validée"],
    ["341","BOURDON","Raphaël","Masters 30","Homme","Validée"],
    ["342","LEON","Romain","Espoirs","Homme","Validée"],
    ["343","SANQUER","Fabien","Masters 30","Homme","Validée"],
    ["344","LE MOAN","David","Seniors","Homme","Validée"],
    ["345","LANDURE","Olol","Masters 40","Homme","Validée"],
    ["346","SCALIGER","Quentin","Cadets","Homme","Validée"],
    ["347","SCALIGER","Cédric","Masters 40","Homme","Validée"],
    ["348","PONS","Hervé","Masters 40","Homme","Validée"],
    ["349","NICOL","Olivier","Masters 40","Homme","Validée"],
    ["350","KERROS","Cyrille","Masters 40","Homme","Validée"],
    ["400","DERRIEN","Pascal","Masters 40","Homme","Validée"],
    ["401","BEGOC","Frederic","Masters 40","Homme","Validée"],
    ["402","BAS","Steeven","Espoirs","Homme","Validée"],
    ["403","DERRIEN","Nathaniel","Juniors","Homme","Validée"],
    ["404","CARRIOU","Thomas","Espoirs","Homme","Validée"],
    ["405","CARRIOU","Maxime","Seniors","Homme","Validée"],
    ["406","RANNOU","Jean-Yves","Masters 50+","Homme","Validée"],
    ["407","LE CAM","Yohann","Pupilles","Homme","Validée"],
    ["408","QUERE","Adri","Masters 30","Homme","Validée"],
    ["409","GUEGUEN GAUTHIER","Gauthier","Espoirs","Homme","Validée"],
    ["410","LE NAOUR","Seb","Masters 40","Homme","Validée"],
    ["411","LE GUEN","ERIC","Masters 50+","Homme","Validée"],
    ["412","DERRIEN","Aymeric","Minimes","Homme","Validée"],
    ["413","LEGRAND","Alan","Cadets","Homme","Validée"],
    ["414","JEZEQUEL","Youen","Minimes","Homme","Validée"],
    ["415","APPÉRÉ","Louen","Minimes","Homme","Validée"],
    ["416","TRAOUEN","Stella","Benjamins","Femme","Validée"],
    ["417","OLLIVIER","Louise","Benjamins","Femme","Validée"],
    ["418","SALAUN","Maely","Benjamins","Femme","Validée"],
    ["419","LE BARZ","Lola","Benjamins","Femme","Validée"],
    ["420","ROUZEAU","Antoine","Minimes","Homme","Validée"],
    ["421","LE GUERN","Kylian","Minimes","Homme","Validée"],
    ["422","GUEGUEN","Aurelien","Minimes","Homme","Validée"],
    ["423","MENEZ","Aymeric","Minimes","Homme","Validée"],
    ["424","","Gautier","Minimes","Homme","Validée"],
    ["425","","Hugo","Minimes","Homme","Validée"],
    ["426","","Ulysse","Minimes","Homme","Validée"],
    ["427","","Colin","Minimes","Homme","Validée"],
    ["428","GABILLET","Solal","Minimes","Homme","Validée"],
    ["429","OLLIVIER","Regis","Masters 30","Homme","Validée"],
    ["430","SALAUN","David","Masters 30","Homme","Validée"],
    ["431","LE DEZ","Julien","Masters 30","Homme","Validée"],
    ["432","CALVÉ","Sébastien","Masters 40","Homme","Validée"],
    ["433","RIOUAL","Christophe","Masters 40","Homme","Validée"],
    ["434","POHER","Evan","Minimes","Homme","Validée"],
    ["435","LE GUYADER","Elouan","Benjamins","Homme","Validée"],
    ["436","CASSOURRET","Johann","Masters 30","Homme","Validée"],
    ["437","LE GUYADER","Ilan","Minimes","Homme","Validée"],
    ["438","SALAUN","Raphael","Minimes","Homme","Validée"],
    ["439","RIVOAL","Paul","Minimes","Homme","Validée"],
    ["440","BALLER","Renald","Masters 40","Homme","Validée"],
    ["441","BALLER","Laurent","Masters 40","Homme","Validée"],
    ["442","GUYOMARC'H","David","Masters 40","Homme","Validée"],
    ["443","GUYOMARC'H","Thierry","Masters 50+","Homme","Validée"],
    ["444","POSTEC","Sébastien","Seniors","Homme","Validée"],
    ["445","LE GOFF","mathieu","Masters 40","Homme","Validée"],
    ["446","MARZIN","Nicolas","Masters 40","Homme","Validée"],
    ["447","NORMAND","Fabrice","Masters 40","Homme","Validée"],
    ["448","LE CAM","Jean-Noël","Masters 50+","Homme","Validée"],
    ["449","LE CAM","Matthieu","Juniors","Homme","Validée"],
    ["450","DOUCET","Raphael","Cadets","Homme","Validée"],
    ["451","LE GALL","Nathan","Minimes","Homme","Validée"],
]